---
- name: Adding backports repository
  apt_repository:
    repo: "deb http://httpredir.debian.org/{{ ansible_os_family | lower }} {{ ansible_distribution_release }}-backports main"
    state: present
    filename: backports.list

- name: Adding apt key for haproxy dedicated repo
  apt_key:
    url: "https://haproxy.debian.net/bernat.debian.org.gpg"
    state: present
  tags: apt-key-add

- name: Adding haproxy dedicated repository
  apt_repository:
    repo: "deb http://haproxy.debian.net {{ ansible_distribution_release }}-backports-1.8 main"
    state: present
    filename: haproxy.list
    update_cache: yes
  tags: update-sources

- name: install heartbeat and haproxy components
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - haproxy=1.8.*
    - heartbeat
    - curl

- name: Configure pacemaker - disable stonith
  shell: crm_attribute --type crm_config --name stonith-enabled --update false

- name: Configure pacemaker  quorum policy
  shell:  crm_attribute --type crm_config --name no-quorum-policy --update ignore

- name: Comment out SysVStartPriority for heartbeat
  lineinfile:
    path: /lib/systemd/system/heartbeat.service
    regexp: 'SysVStartPriority='
    state: absent
    owner: root
    group: root
    mode: 0644

- name: configure rsyslog - load imudp
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '#module\(load="imudp"\)'
    line: 'module(load="imudp")'
    state: present
  notify: restart rsyslog

- name: configure rsyslog - set imudp to port 514
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '#input\(type="imudp" port="514"\)'
    line: 'input(type="imudp" port="514")'
    state: present
  notify: restart rsyslog

- name: configure heartbeat
  template:
    src: ha.cf.j2
    dest: /etc/ha.d/ha.cf
    owner: root
    group: root
    mode: 0644

- name: configure authkey
  template:
    src: authkeys.j2
    dest: /etc/ha.d/authkeys
    owner: root
    group: root
    mode: 0600

- name: configure haresources
  template:
    src: haresources.j2
    dest: /etc/ha.d/haresources
    owner: root
    group: root
    mode: 0644
  notify: restart heartbeat

- name: install floating ip assigner
  copy:
    src: assign-ip
    dest: /usr/local/bin/assign-ip
    owner: root
    group: root
    mode: 0755

- name: install floating ip manager
  template:
    src: floatip.j2
    dest: /etc/init.d/floatip
    owner: root
    group: root
    mode: 0755

- name: Enable floatip on bootup
  systemd:
    name: floatip.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: configure haproxy service for galera
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644

- name: enable haproxy
  lineinfile:
    dest: /etc/default/haproxy
    state: present
    regexp: 'ENABLED=0'
    line: 'ENABLED=1'
    owner: root
    group: root
    mode: 0644
  notify: restart haproxy

