galaxy_info:
  author: cmndrsp0ck
  description: haproxy configured to load balance queries among MariaDB Galera cluster
  company: N/A

  license: GPL-3.0

  min_ansible_version: 2.4

  github_branch: master

  platforms:
    - name: Debian
      versions:
      - stretch

  galaxy_tags:
    - haproxy
    - DigitalOcean

dependencies: []
